// Mocks generated by Mockito 5.4.4 from annotations
// in multitracks_df_pro/test/features/player_mixer/presentation/stores/setlist_config_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:multitracks_df_pro/core/audio_engine/iaudio_engine_service.dart'
    as _i2;
import 'package:multitracks_df_pro/features/player_mixer/domain/entities/track.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IAudioEngineService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAudioEngineService extends _i1.Mock
    implements _i2.IAudioEngineService {
  MockIAudioEngineService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<Duration> get onPreviewPosition => (super.noSuchMethod(
        Invocation.getter(#onPreviewPosition),
        returnValue: _i3.Stream<Duration>.empty(),
      ) as _i3.Stream<Duration>);

  @override
  _i3.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> seekTo(Duration? timestamp) => (super.noSuchMethod(
        Invocation.method(
          #seekTo,
          [timestamp],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> loadPreview(List<_i4.Track>? tracks) => (super.noSuchMethod(
        Invocation.method(
          #loadPreview,
          [tracks],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void clearAllTracks() => super.noSuchMethod(
        Invocation.method(
          #clearAllTracks,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void playPreview() => super.noSuchMethod(
        Invocation.method(
          #playPreview,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pausePreview() => super.noSuchMethod(
        Invocation.method(
          #pausePreview,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackVolume(
    String? trackId,
    double? volume,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackVolume,
          [
            trackId,
            volume,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackPan(
    String? trackId,
    double? pan,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackPan,
          [
            trackId,
            pan,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackMute(
    String? trackId,
    bool? isMuted,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackMute,
          [
            trackId,
            isMuted,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackSolo(
    String? trackId,
    bool? isSolo,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackSolo,
          [
            trackId,
            isSolo,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackEq({
    required String? trackId,
    required int? bandIndex,
    required double? frequency,
    required double? gain,
    required double? q,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackEq,
          [],
          {
            #trackId: trackId,
            #bandIndex: bandIndex,
            #frequency: frequency,
            #gain: gain,
            #q: q,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackTempo(
    String? trackId,
    double? factor,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackTempo,
          [
            trackId,
            factor,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackPitch(
    String? trackId,
    int? semitones,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackPitch,
          [
            trackId,
            semitones,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMasterVolume(double? volume) => super.noSuchMethod(
        Invocation.method(
          #setMasterVolume,
          [volume],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMasterEq({
    required int? bandIndex,
    required double? frequency,
    required double? gain,
    required double? q,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setMasterEq,
          [],
          {
            #bandIndex: bandIndex,
            #frequency: frequency,
            #gain: gain,
            #q: q,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<double> getWaveformData(
    String? trackId,
    int? numBins,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWaveformData,
          [
            trackId,
            numBins,
          ],
        ),
        returnValue: <double>[],
      ) as List<double>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
