// Mocks generated by Mockito 5.4.4 from annotations
// in multitracks_df_pro/test/features/player_mixer/presentation/stores/setlist_config_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:multitracks_df_pro/core/audio_engine/iaudio_engine_service.dart'
    as _i3;
import 'package:multitracks_df_pro/features/player_mixer/domain/entities/music.dart'
    as _i7;
import 'package:multitracks_df_pro/features/player_mixer/domain/entities/setlist.dart'
    as _i2;
import 'package:multitracks_df_pro/features/player_mixer/domain/entities/setlist_item.dart'
    as _i9;
import 'package:multitracks_df_pro/features/player_mixer/domain/entities/track.dart'
    as _i5;
import 'package:multitracks_df_pro/features/player_mixer/domain/repositories/imusic_repository.dart'
    as _i6;
import 'package:multitracks_df_pro/features/player_mixer/domain/services/setlist_export_service.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSetlist_0 extends _i1.SmartFake implements _i2.Setlist {
  _FakeSetlist_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAudioEngineService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAudioEngineService extends _i1.Mock
    implements _i3.IAudioEngineService {
  MockIAudioEngineService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<Duration> get onPreviewPosition => (super.noSuchMethod(
        Invocation.getter(#onPreviewPosition),
        returnValue: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seekTo(Duration? timestamp) => (super.noSuchMethod(
        Invocation.method(
          #seekTo,
          [timestamp],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadPreview(List<_i5.Track>? tracks) => (super.noSuchMethod(
        Invocation.method(
          #loadPreview,
          [tracks],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void clearAllTracks() => super.noSuchMethod(
        Invocation.method(
          #clearAllTracks,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void playPreview() => super.noSuchMethod(
        Invocation.method(
          #playPreview,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pausePreview() => super.noSuchMethod(
        Invocation.method(
          #pausePreview,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackVolume(
    String? trackId,
    double? volume,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackVolume,
          [
            trackId,
            volume,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackPan(
    String? trackId,
    double? pan,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackPan,
          [
            trackId,
            pan,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackMute(
    String? trackId,
    bool? isMuted,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackMute,
          [
            trackId,
            isMuted,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackSolo(
    String? trackId,
    bool? isSolo,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackSolo,
          [
            trackId,
            isSolo,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackEq({
    required String? trackId,
    required int? bandIndex,
    required int? filterType,
    required double? frequency,
    required double? gain,
    required double? q,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackEq,
          [],
          {
            #trackId: trackId,
            #bandIndex: bandIndex,
            #filterType: filterType,
            #frequency: frequency,
            #gain: gain,
            #q: q,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackTempo(
    String? trackId,
    double? factor,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackTempo,
          [
            trackId,
            factor,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackPitch(
    String? trackId,
    int? semitones,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackPitch,
          [
            trackId,
            semitones,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMasterVolume(double? volume) => super.noSuchMethod(
        Invocation.method(
          #setMasterVolume,
          [volume],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMasterEq({
    required int? bandIndex,
    required int? filterType,
    required double? frequency,
    required double? gain,
    required double? q,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setMasterEq,
          [],
          {
            #bandIndex: bandIndex,
            #filterType: filterType,
            #frequency: frequency,
            #gain: gain,
            #q: q,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  double getTrackVolumeDb(String? trackId) => (super.noSuchMethod(
        Invocation.method(
          #getTrackVolumeDb,
          [trackId],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double getMasterVolumeDb() => (super.noSuchMethod(
        Invocation.method(
          #getMasterVolumeDb,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Future<List<double>> getWaveformData(
    String? trackId,
    int? numBins,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWaveformData,
          [
            trackId,
            numBins,
          ],
        ),
        returnValue: _i4.Future<List<double>>.value(<double>[]),
      ) as _i4.Future<List<double>>);

  @override
  _i4.Future<List<double>> extractWaveformPeaksFromFile(
    String? filePath,
    int? numBins,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractWaveformPeaksFromFile,
          [
            filePath,
            numBins,
          ],
        ),
        returnValue: _i4.Future<List<double>>.value(<double>[]),
      ) as _i4.Future<List<double>>);

  @override
  _i4.Future<List<double>> getWaveformPeaks(
    String? filePath, {
    int? numBins = 400,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWaveformPeaks,
          [filePath],
          {#numBins: numBins},
        ),
        returnValue: _i4.Future<List<double>>.value(<double>[]),
      ) as _i4.Future<List<double>>);

  @override
  void renderTrackOffline({
    required String? trackId,
    required String? inputPath,
    required String? outputPath,
    required double? tempo,
    required double? pitch,
    required double? volume,
    required double? pan,
    required List<_i3.RenderEqBand>? eqBands,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #renderTrackOffline,
          [],
          {
            #trackId: trackId,
            #inputPath: inputPath,
            #outputPath: outputPath,
            #tempo: tempo,
            #pitch: pitch,
            #volume: volume,
            #pan: pan,
            #eqBands: eqBands,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  double getRenderProgress(String? trackId) => (super.noSuchMethod(
        Invocation.method(
          #getRenderProgress,
          [trackId],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  void cancelRender(String? trackId) => super.noSuchMethod(
        Invocation.method(
          #cancelRender,
          [trackId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IMusicRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMusicRepository extends _i1.Mock implements _i6.IMusicRepository {
  MockIMusicRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveMusic(_i7.Music? music) => (super.noSuchMethod(
        Invocation.method(
          #saveMusic,
          [music],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Music>> getAllMusic() => (super.noSuchMethod(
        Invocation.method(
          #getAllMusic,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Music>>.value(<_i7.Music>[]),
      ) as _i4.Future<List<_i7.Music>>);

  @override
  _i4.Future<void> deleteMusic(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMusic,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Music>> getMusicByIds(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMusicByIds,
          [ids],
        ),
        returnValue: _i4.Future<List<_i7.Music>>.value(<_i7.Music>[]),
      ) as _i4.Future<List<_i7.Music>>);

  @override
  _i4.Future<void> saveSetlist(_i2.Setlist? setlist) => (super.noSuchMethod(
        Invocation.method(
          #saveSetlist,
          [setlist],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Setlist>> getAllSetlists() => (super.noSuchMethod(
        Invocation.method(
          #getAllSetlists,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Setlist>>.value(<_i2.Setlist>[]),
      ) as _i4.Future<List<_i2.Setlist>>);

  @override
  _i4.Future<void> deleteSetlist(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSetlist,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SetlistExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetlistExportService extends _i1.Mock
    implements _i8.SetlistExportService {
  MockSetlistExportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Setlist> exportSetlist(
    _i2.Setlist? setlist, {
    void Function(_i8.ExportProgress)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportSetlist,
          [setlist],
          {#onProgress: onProgress},
        ),
        returnValue: _i4.Future<_i2.Setlist>.value(_FakeSetlist_0(
          this,
          Invocation.method(
            #exportSetlist,
            [setlist],
            {#onProgress: onProgress},
          ),
        )),
      ) as _i4.Future<_i2.Setlist>);

  @override
  bool shouldBypassRender(
    _i9.SetlistItem? item,
    _i5.Track? track,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldBypassRender,
          [
            item,
            track,
          ],
        ),
        returnValue: false,
      ) as bool);
}
